## ট্রেইন ও টেস্ট ভাগ করে ইভ্যালুয়েশন

#### মডেল ইভাল্যুয়েশনের ধারণা"

1. পুরো ডেটাসেটকে ভাগ করে ফেলি দুভাগে। ক. ট্রেনিং সেট খ. টেস্ট সেট।
 
2. মডেলকে ট্রেনিং করাবো "ট্রেনিং সেট" দিয়ে।

3. মডেলকে টেস্ট করবো "টেস্ট সেট" দিয়ে। সেটাই ইভ্যালুয়েট করবে কেমন করছে মডেলটা।

4. আমাদের সাইকিট-লার্নে এই কাজ করার জন্য train_test_split নামে একটা ফাংশন তৈরি করে দেয়া হয়েছে কাজের সুবিধার্থে। শুধুমাত্র কনভেনশনটা জানলেই চলবে।

আইরিস ডেটাসেট নিয়ে কাজ করার আগে একটা উদাহরণ দেখি। সাইকিট লার্ন ডকুমেন্টেশন থেকে নেয়া। আগে আপনাদেরকে দেখিয়ে নিয়ে আসি X এবং y এর ভেতরে কী আছে?

In [1]:
import numpy as np

X, y = np.arange(10).reshape((5, 2)), range(5)

X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [2]:
# এখন দেখি কি আছে y এর ভেতর। 
y

range(0, 5)

In [3]:
# এর মানে ০ থেকে ৫টা সংখ্যা, লিস্ট কমান্ড দিয়ে দেখি বরং 
list(y)

[0, 1, 2, 3, 4]

এখন আসি কাজের কাজে। কষ্ট করে X, y ম্যানুয়ালি আলাদা না করে ডেকে নিয়ে আসি train_test_split ফাংশনকে। সাইকিট লার্নের model_selection মডিউল থেকে। আমি যদি আলাদা করে কিছু না বলি, তাহলে সে আমাদের এই ৫ লাইনের ডেটাকে ৭৫% ট্রেনিং আর ২৫% টেস্ট ডেটাসেটে ভাগ করবে।

In [4]:
from sklearn.model_selection import train_test_split

একটু ভালো করে লক্ষ্য করলেই দেখবেন নিচের কমান্ডটা একটা সাইকিট লার্ন কনভেনশন। এই স্টাইলে ফলো করে সবাই। এটাই ব্যবহার করবো আমরা। শুরুতে কপি করে চালাবো এই কনভেনশন। train_test_split পুরো ডেটাকে ট্রেনিং আর টেস্ট সেটে ভাগ করার আগে দৈবচয়নের মাধ্যমে (random_state) শাফল করে নেয় কাজের সুবিধার্থে। মনে আছে শুরুতে টার্গেট ভেক্টর 0,0,0 এর পর 1,1,1 অথবা 2,2,2 হওয়ার কারণে শাফল জরুরি। তবে, random_state=? ভ্যালু হিসেবে যা ব্যবহার করবেন সেটাকে এক রাখতে হবে পুরো এক্সারসাইজে। মনে রাখুন X ভাগ হবে X_train, X_test দুভাগে। সেখানে y হবে y_train, y_test দুভাগে।

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

চলুন দেখি X_train, X_test, y_train এবং y_test মধ্যে কী আছে? খেয়াল করুন কিভাবে পুরো ডেটাসেট ভাগ হয়েছে?

In [8]:
X_train # ৫টা রেকর্ডের মধ্যে ৩টা এসেছে এখানে 

array([[2, 3],
       [8, 9],
       [4, 5]])

In [9]:
y_train # টার্গেট ভেক্টর আসতে হবে ওই ৩টাই 

[1, 4, 2]

In [10]:
X_test

array([[0, 1],
       [6, 7]])

In [11]:
y_test

[0, 3]

In [12]:
train_test_split(y,shuffle=True)

[[2, 0, 3], [1, 4]]

In [13]:
train_test_split(y,shuffle=True)

[[3, 4, 0], [1, 2]]

In [14]:
train_test_split(y,shuffle=False)

[[0, 1, 2], [3, 4]]

In [15]:
train_test_split(y,shuffle=False)

[[0, 1, 2], [3, 4]]

দেখেছেন তো কিভাবে পুরো ডেটাসেট ভাগ হয়ে গেছে? এখন আসি আইরিস ডেটাসেটে। শুরুতে আগের গল্প। পপুলেট করে নেই ফিচার আর টার্গেট রেসপন্স।

### ধাপ ১

In [16]:
from sklearn import datasets
iris=datasets.load_iris()

In [19]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

In [20]:
print(X.shape)

(150, 4)


In [21]:
print(y.shape)

(150,)


### ধাপ ২

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

এই জিনিস থেকে কী পাবো আমরা?

1. আলাদা আলাদা ডেটা দিয়ে মডেলকে ট্রেইন এবং টেস্ট করানো যাবে।

2. টেস্ট সেটের 'রেসপন্স ভ্যালু' আমরা যেহেতু জানি, সেজন্য সেটার পারফরম্যান্স জানা যাবে।

3. টেস্টিং অ্যাক্যুরেসি ভালো হবে যখন দুটো আলাদা আলাদা ডেটাসেট। মডেলটা 'জেনারেলাইজড' হলো নতুন আউট অফ স্যাম্পল ডেটা নিয়ে কাজ করার জন্য।

4. ডিফল্ট সেটিংস ধরে রেকর্ডকে ভাগ করে ৭৫% ডেটাকে ট্রেনিং আর ২৫% ডেটাকে টেস্ট ডেটাসেটে ভাগ হয়ে যাবে। ৭৫% হচ্ছে ১১২টা রেকর্ড। ২৫% হচ্ছে ৩৮টা রেকর্ড।

In [23]:
# নতুন  X অবজেক্টগুলোর রেকর্ড সংখ্যা 
print(X_train.shape)

(112, 4)


In [24]:
print(X_test.shape)

(38, 4)


In [25]:
# নতুন  y অবজেক্টগুলোর রেকর্ড সংখ্যা 

print(y_train.shape)

(112,)


In [26]:
print(y_test.shape)

(38,)


ধরুন, আপনার বন্ধু নাছোড়বান্দা। সে ডিফল্ট সেটিংস নিয়ে সন্তুষ্ট নয়। তার কথা হচ্ছে ট্রেনিং আর টেস্ট সেট ভাগ করতে চায় ৬০-৪০% ভাগে। তার জন্য আপনাকে যোগ করতে হবে test_size=0.4 মানে ৪০%।

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [30]:
print(X_train.shape)

(90, 4)


In [31]:
print(y_train.shape)

(90,)


In [32]:
print(X_test.shape)

(60, 4)


In [33]:
print(y_test.shape)

(60,)


### ধাপ ৩

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn=KNeighborsClassifier(n_neighbors=3)

In [36]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

### ধাপ ৪

In [37]:
y_pred = knn.predict(X_test)

In [39]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


### যদি "কে-নিয়ারেস্ট নেইবার্স" ক্লাসিফায়ারের নেইবার ৫ হয়

In [40]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667
